---
title: "COVID-19 Transmission in Malaysia"
author: |
  | Kamarul Imran Musa
  | Associate Professor (Epidemiology and Statistics)
date: "`r Sys.Date()`"
output:
  html_document:
     theme: united
     highlight: tango
     toc: yes
     toc_depth: '3'
     toc_float: yes
     number_sections: true
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
---

\newpage
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r}
library(tidyverse)
library(incidence)
library(EpiEstim)
library(readxl)
library(lubridate)
library(DT)
```


# Read data

```{r}
excel_sheets('covid19_mph.xlsx')
mys <- read_excel('covid19_mph.xlsx',
                  sheet = 1)
```

# Analysis for Malaysia

```{r}
mys2 <- mys %>%
  select(Time = Tarikh, I = Total) %>%
  filter(Time > '2020-03-03' & Time < '2021-01-01')
```

# Calculate R

Using serial interval from Du, Z, et al

```{r}
mys_parametric_si_du <- estimate_R(mys2, 
                                method = "parametric_si",
                                config = make_config(list(mean_si = 3.96, 
                                                          std_si = 4.75)))
```

# Date and Time 

To get days from Day 1 of 10 or more cases (4 March 2020) to

- 1st MCO 
- 2nd MCO and the rest

Link https://en.wikipedia.org/wiki/Malaysian_movement_control_order 


```{r}
difftime(ymd('2020-03-17'), ymd('2020-03-03'), 'days')
difftime(ymd('2020-03-31'), ymd('2020-03-03'), 'days')
difftime(ymd('2020-04-14'), ymd('2020-03-03'), 'days')
difftime(ymd('2020-04-28'), ymd('2020-03-03'), 'days')
difftime(ymd('2020-05-03'), ymd('2020-03-03'), 'days')
difftime(ymd('2020-06-09'), ymd('2020-03-03'), 'days')
difftime(ymd('2020-12-31'), ymd('2020-03-03'), 'days')
```
# Plot incidence

```{r}
p_I_du <- plot(mys_parametric_si_du, "incid") 
p_I_du
p_I_du + theme_bw() + 
  geom_vline(xintercept = 14, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 28, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 42, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 56, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 61, colour = 'green', size = 1.2) +
  geom_vline(xintercept = 98, colour = 'green', size = 1.2) +
  geom_text(aes(x = 13, label = '\nMCO Phase 1', y=2000),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 27, label = '\nMCO Phase 2', y= 2000),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 41, label = '\nMCO Phase 3', y=2000),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 55, label = '\nMCO Phase 4', y=2000),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 60, label = '\nCMCO ', y=2500),
            colour="green", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 97, label = '\nRMCO', y=2500),
            colour="green", angle=90, hjust = 1, text=element_text(size=11)) +
  labs(caption = "Day 1 starts on March,4 2020")
```

# Plot R

```{r}
p_R_du <- plot(mys_parametric_si_du, "R") 
p_R_du + theme_bw() + 
  geom_vline(xintercept = 14, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 28, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 42, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 56, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 61, colour = 'green', size = 1.2) +
  geom_vline(xintercept = 98, colour = 'green', size = 1.2) +
  geom_text(aes(x = 13, label = '\nMCO Phase 1', y=3.2),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 27, label = '\nMCO Phase 2', y= 3.2),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 41, label = '\nMCO Phase 3', y=3.2),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 55, label = '\nMCO Phase 4', y=3.2),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 60, label = '\nCMCO ', y=2),
            colour="green", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 97, label = '\nRMCO', y=2),
            colour="green", angle=90, hjust = 1, text=element_text(size=11)) +
  labs(caption = "Day 1 starts on March,4 2020")

```
# R values

```{r}
mys_R <- mys_parametric_si_du$R %>%
  datatable()
mys_R
write_csv(mys_parametric_si_du$R, 'R_Malaysia.csv')
```


# Analysis for Kelantan

```{r}
kel <- read_excel('covid19_mph.xlsx',
                  sheet = "Kelantan")
```


```{r}
kel2 <- kel %>%
  select(Time = Tarikh, I = Total) %>%
  filter(Time > '2020-03-03' & Time < '2021-01-01')
```

# Calculate R

Using serial interval from Du, Z, et al

```{r}
kel_parametric_si_du <- estimate_R(kel2, 
                                method = "parametric_si",
                                config = make_config(list(mean_si = 3.96, 
                                                          std_si = 4.75)))
```

# Plot indence


```{r}
kel_p_I_du <- plot(kel_parametric_si_du, "incid") 
kel_p_I_du + theme_bw() + 
  geom_vline(xintercept = 14, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 28, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 42, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 56, colour = 'red', size = 1.2) +
  geom_vline(xintercept = 61, colour = 'green', size = 1.2) +
  geom_vline(xintercept = 98, colour = 'green', size = 1.2) +
  geom_text(aes(x = 13, label = '\nMCO Phase 1', y=50),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 27, label = '\nMCO Phase 2', y= 50),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 41, label = '\nMCO Phase 3', y=50),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 55, label = '\nMCO Phase 4', y=50),
            colour="blue", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 60, label = '\nCMCO ', y=20),
            colour="green", angle=90, hjust = 1, text=element_text(size=11)) +
  geom_text(aes(x = 97, label = '\nRMCO', y=20),
            colour="green", angle=90, hjust = 1, text=element_text(size=11)) +
  labs(caption = "Day 1 starts on March,4 2020")
```

# Plot R

Wide 95% CI due to small number of cases

```{r}
kel_p_R_du <- plot(kel_parametric_si_du, "R") 
kel_p_R_du + theme_bw() + 
  labs(caption = "Day 1 starts on March,4 2020")

```


# R values

```{r}
kel_R <- kel_parametric_si_du$R %>%
  datatable()
kel_R
write_csv(kel_parametric_si_du$R, 'R_Kel.csv')
```